# Generated by Django 5.1.6 on 2025-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpost_company_name_alter_jobpost_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
