# Generated by Django 5.1.6 on 2025-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobpost_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='Unknow', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
