# Generated by Django 5.1.6 on 2025-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobpost_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
