# Generated by Django 5.1.6 on 2025-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobpost_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
